//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataService.DataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public int CylinderVolume { get; set; }
        public int NumberOfSeats { get; set; }
        public string Color { get; set; }
        public int Length { get; set; }
        public int Width { get; set; }
        public int DistanceBetweenAxes { get; set; }
        public int Kilowatts { get; set; }
        public FuelType FuelType { get; set; }
        public System.DateTime FirstUseDate { get; set; }
        public int Brand { get; set; }
        public int Weight { get; set; }
    }
}
