//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataService.DataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int Id { get; set; }
        public Product Product { get; set; }
        public string ClaimType { get; set; }
        public System.DateTime Date { get; set; }
        public Gender Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Venue { get; set; }
        public string Situation { get; set; }
        public string RoadType { get; set; }
        public string MunicipalityClaim { get; set; }
        public string MunicipalityPolicyholder { get; set; }
        public int LocationId { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Location Location { get; set; }
    }
}
