//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataService.DataManagement
{
    using System;
    
    public enum FuelType : int
    {
        Benzine = 1,
        Diesel = 2,
        Undefined = 0
    }
}
