//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageContent
    {
        public int ImageId { get; set; }
        public System.DateTime ImageDateTime { get; set; }
        public byte[] ImageData { get; set; }
    }
}
