//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Web.UI;

namespace SignalRServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iteraphotobooth_dbEntities : DbContext
    {
        public iteraphotobooth_dbEntities()
            : base("name=iteraphotobooth_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImageContent> ImageContent { get; set; }

        public void Add(ImageContent imageContent)
        {
            ImageContent.Add(imageContent);
        }

        public ImageContent GetById(int imageId)
        {
            return ImageContent.SingleOrDefault(x => x.ImageId == imageId);
        }

        public IEnumerable<ImageContent> GetAll()
        {
            return ImageContent.ToList();
        }
    }
}
